bboard/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='')),

]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

main/urls.py
from django.urls import path

from .views import index, other_page

app_name = 'main'
urlpatterns = [
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index')
]

main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

main/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template

def index(request):
    return render(request, 'main/index.html')


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))

main/templates/layout/basic.html
{% load bootstrap4 %}
{% load static %}
<! DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type"
          content="text/html; charset=utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=l, shrink-to-fit=no">
    <title>{% block title %}Главная{% endblock %} - Доска объявлений</title>
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css"
          href="{% static 'main/style.css' %}">
    {% bootstrap_javascript jquery='slim' %}
</head>
<body class="container-fluid">
<header class="mЬ-4">
    <h1 class="display-1 text-center">Объявления</h1>
</header>
<div class="row">
    <ul class="col nav justify-content-end border">
        <li class="nav-item"><a class="nav-link" href="#">Регистрация</a></li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle"
               data-toggle="dropdown" href="#"
               role="button" aria-haspopup="true"
               aria-expanded="false">Профиль</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Moи объявления</a>
                <a class="dropdown-item" href="#">Изменить личные данные</a>
                <a class="dropdown-item" href="#">Изменить пароль</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Выйти</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Удалить</a>
            </div>
        </li>
        <li class="nav-item"><a class="nav-link"
                                href="#">Bxoд</a></li>
    </ul>
</div>
<div class="row">
    <nav class="col-md-auto nav flex-column border">
        <a class="nav-link root"
           href="{% url 'main:index' %}">Главная</a>
        <span class=" nav-link root font-weight-bold">
        Недвижимость</span>
        <a class="nav-link" href="#">Жилье</a>
        <a class="nav-link" href="#">Склады</a>
        <a class="nav-link" href="#">Гаражи</a>
        <span class="nav-link root font-weight-bold" href="#">Транспорт</span>
        <a class="nav-link" href="#">Легковой</a>
        <a class="nav-link" href="#">Грузовой</a>
        <a class="nav-link root" href="{% url 'main:other' page='about' %}">О сайте</a>
    </nav>
    <section class="col border ру-2">
        {% bootstrap_messages %}
        {% block content %}
        {% endblock %}
    </section>
</div>
<footer class="mt-3">
    <p class="text-right font-italic">&copy; читатели, 2018 г. </p>
</footer>
</body>
</html>

main/templates/main/about.html
{% extends "layout/basic.html" %}

{% block title %}О сайте{% endblock %}

{% block content %}
<h2>О сайте</h2>
<p>Сайт для публикации объявлений о продаже, разбитых на рубрики.</p>
<p>Все права принадлежат МНЕ </p>
{% endblock %}

main/templates/main/index.html
{% extends "layout/basic.html" %}

{% block content %}
<h2>Последние 10 объявлений</h2>
{% endblock %}